esphome:
  name: lamp
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .wds.local
  use_address: lamp.wds.local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lamp Fallback Hotspot"
    password: "KmHcrXImT8Xu"

# Enable Home Assistant API.
api:

  # Enable over-the-air updates.
ota:

captive_portal:

  # Enable Web server.
web_server:
  port: 80

   # Enable logging
logger:

  # Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  # Uptime sensor.
  - platform: uptime
    name: Zolder Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Zolder WiFi Signal
    update_interval: 60s

light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: D8
    num_leds: 244
    rgb_order: BRG
    name: "FastLED WS2812B Light"