esphome:
  name: slaapkamer2
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .wds.local
  use_address: motiondetector1.wds.local

    # Enable fallback hotspot (captive portal) in case wifi connection fails

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Slaapkamer2 Fallback Hotspot"
    password: "EHxZKWLZg8GL"

# Enable Home Assistant API.
api:

  # Enable over-the-air updates.
ota:

captive_portal:

  # Enable Web server.
web_server:
  port: 80

   # Enable logging
logger:

  # Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  # Uptime sensor.
  - platform: uptime
    name: Zolder Uptime

  # Temperature
  - platform: dht
    pin: 14
    model: AM2302
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Zolder WiFi Signal
    update_interval: 60s
    filters:
    - sliding_window_moving_average:
        window_size: 15
        send_every: 15

  - platform: mhz19
    id: slaapkamer2mhz19
    co2:
      name: "MH-Z19 CO2 Value"
    temperature:
      name: "MH-Z19 Temperature"
    update_interval: 300s
    automatic_baseline_calibration: false

switch:
  - platform: template
    name: "MH-Z19 Slaakamer 2 ABC"
    optimistic: true
    on_turn_on:
      mhz19.abc_enable: slaapkamer2mhz19
    on_turn_off:
      mhz19.abc_disable: slaapkamer2mhz19

uart:
  rx_pin: GPIO03
  tx_pin: GPIO01
  baud_rate: 9600